import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme";
import "./globals.css";
import PreloadAssets from "@/components/tools/preload";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Phichayoot Boonton",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Preload Images */}
        <link rel="preload" as="image" href="/images/about-me/about-me-3.jpg" />
        <link rel="preload" as="image" href="/images/about-me/about-me-2.jpg" />
        <link rel="preload" as="image" href="/images/about-me/about-me-1.jpg" />
        <link
          rel="preload"
          as="image"
          href="/images/about-me/about-me-modal.jpg"
        />
        <link
          rel="preload"
          as="image"
          href="/images/project/gaysorn/gaysorn-icon.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/project/land-4-thai/land-4-thai-logo-app.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/project/land-4-thai/land-4-thai-screen.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/project/land-4-thai/land-4-thai-overlay-preview.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/project/rfp/rfp-award-screen.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/project/rfp/rfp-icon.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/project/rfp/rfp-home-screen.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/skills/database/sequelize.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/skills/frontend/nextjs.png"
        />
        <link rel="preload" as="image" href="/images/skills/frontend/dnd.png" />
        <link
          rel="preload"
          as="image"
          href="/images/skills/frontend/skills-fontend-not-use.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/skills/frontend/nextjs-dark.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/skills/frontend/antd.png"
        />
        <link rel="preload" as="image" href="/images/skills/frontend/gql.png" />
        <link
          rel="preload"
          as="image"
          href="/images/skills/frontend/zustand.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/skills/backend/phpmyadmin.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/skills/backend/nestJs.png"
        />
        <link rel="preload" as="image" href="/images/skills/backend/php.png" />
        <link rel="preload" as="image" href="/images/skills/ai/claude.png" />
        <link rel="preload" as="image" href="/images/skills/ai/chatGPT.png" />
        <link rel="preload" as="image" href="/images/skills/utility/git.png" />
        <link
          rel="preload"
          as="image"
          href="/images/skills/utility/python.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/skills/utility/tailwind.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/skills/utility/skills-python.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/skills/utility/figma.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/skills/utility/skills-tailwind.png"
        />
        <link rel="preload" as="image" href="/images/banner/a-banner.png" />
        <link
          rel="preload"
          as="image"
          href="/images/phone-layout/ipad-layout.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/phone-layout/macbook-layout.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/phone-layout/android-layout.png"
        />
        <link
          rel="preload"
          as="image"
          href="/images/phone-layout/iphone-layout.png"
        />

        {/* Preload Videos */}
        <link
          rel="preload"
          as="video"
          href="/images/project/karaoke/karaoke-iphone-remote.mp4"
          type="video/mp4"
        />
        <link
          rel="preload"
          as="video"
          href="/images/project/karaoke/karaoke-ipad-screen.mp4"
          type="video/mp4"
        />
        <link
          rel="preload"
          as="video"
          href="/images/project/gaysorn/gaysorn-preview.mp4"
          type="video/mp4"
        />
        <link
          rel="preload"
          as="video"
          href="/images/skills/frontend/skills-frontend.mp4"
          type="video/mp4"
        />
        <link
          rel="preload"
          as="video"
          href="/images/skills/backend/skills-backend-bg-2.mp4"
          type="video/mp4"
        />
        <link
          rel="preload"
          as="video"
          href="/images/banner/b-banner.mp4"
          type="video/mp4"
        />
      </Head>
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
          <PreloadAssets>{children}</PreloadAssets>
        </ThemeProvider>
      </body>
    </html>
  );
}
